travis:
  secure:
    BINSTAR_TOKEN: bY92elXx9TTD/V2RfQu0TshqG/JsMitkbamw2U66/RAPPXc7H22BvwUSzUQkcoXOerfM1QVyUQ3qq6Yms5Ogutf3KH7pdBydadI8JFIgpl93pWTjTmyd5+rmAkNPB2D9GvlKLGdvK51gu6eiMzNC9THy6bFCeeDr62Dos6QGWcEWXf2E4gtO5tLYGSl534fjwOe2eWLUTNXrl5hfWnyyMpoJ9c/V/G5eo3e/NaQwpwxYW4uQWFi8UUKyScD+jrf28o4adEba0WARQgDz7Tg42nfr23s8o8b4ktpPHkP+cMiTW5dMfHfP5uWEvgKynDfGNIdNMY0R40c7fD5TLAymlPXFaWtgxLJgDOp30gdjo89DyDqFhygTNZoesZM7js874Gaq1lwpSJUD77xTUBMtHIxcc6I82iz6x3SaD/6E2gTE49M6/wTpQqMSCB+rL8C6Ftn0vB+oFfBiC6VRDTaGbyWDJP0GigVoQibmAoltjBCGgEcCdkm0UCnDABvhahfXwDU5rkuvaHLlP0v4GgQ6I3YnTEwlj5RuhSswg6fDX/hPchneeGJyRUWtU6e+zX2xOOGlGJgDo+hunumpSixlgEPQE/MGUBWHtnaajbEs3jKhvui1MofaNqytI9kWLITQ8PL6SGXqB0jWJHpkIEOZ3TAB0WQ2sKl5Xb0NGoFSFaU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
